### ISSUE TITLE
komentarz do SFML-owe zabawy #5

### ISSUE THREAD

**Issue by purrchawka** [CppPolska/MarioEdit#8]
Ponieważ na waszym blogu nie da się komentować, to napiszę tu.

Nie powinieneś używać wątków do animacji kafelków, bo jest to niepotrzebne, a po drugie, robisz to źle -  program ma niezdefiniowane zachowanie z powodu data race.

Poza tym, klasa Tile ma trzy różne definicje, to narusza regułę ODR i również prowadzi do niezdefiniowanego zachowania.

**Comment by senghe** [comment]
Hej @purrchawka! Dzięki za rady. Zrobiłem trochę zmian w ostatnim czasie, dorzuciłem mutexy, które trochę pilnują data race. Odnośnie potrzebności użycia wątków - chciałem sprawdzić, jak to będzie działało, i póki co nie mam z tym problemu.

Co do definicji klasy Tile - możesz rozwinąć temat nieco bardziej?

PS. Nie jestem zawodowym programistą C++. Całkiem możliwe, że mogę nie wiedzieć o czymś, o czym Ty wiesz :)

**Comment by purrchawka** [comment]
> trochę pilnują data race

Albo jest data race albo go nie ma. Nie ma trochę. Zmienne `Tile::scalePromotion`, `SmoothAnimation::isRunningFlag`, `SmoothAnimation::isStopped` są podejrzane.  A gdybyś nie używał wątków, to by nie było takich problemów.

> Co do definicji klasy Tile - możesz rozwinąć temat nieco bardziej?

W iteration-4 w plikach:
`src/classes/Tile.hpp`
`src/classes/Animation/SmoothAnimation/HightlightTileAnimation.cpp`
`src/classes/Animation/SmoothAnimation/UndoHightlightTileAnimation.cpp`
były różne definicje tej samej klasy Tile. W iteration-5 już tego nie widzę.

A swoją drogą, naprawdę zaszalałeś z  tymi shared_pointerami.

**Comment by purrchawka** [comment]
Rozważ jeszcze taki scenariusz: wątek utworzony w `HighlightTileAnimation::run` animuje sobie kafelek, a Ty właśnie zamykasz aplikację i kafelek przestaje istnieć. Co wtedy ten biedny wątek ma zrobić? Zrezygnuj z animacji w osobnych wątkach. Wątek główny jest od tego.

> Co do definicji klasy Tile - to nie były definicje, tylko deklaracje.

To były definicje, patrz:
```
class Tile {

public:

    float scalePromotion;

    void rescaleCenter();
    void correctCorners();
};
```
```
class Tile {

public:

    float scalePromotion;
    void snapToGrid();
    void rescaleToWindowBound();
};
```
```
class Tile
{

public:

    enum Event {
        MouseOver,
        MouseEnter,
        MouseLeave,
        StartDrag,
        Drag,
        Drop,
    };

    static void setWindow(std::shared_ptr<sf::RenderWindow>& window);
    //itd...
```

**Comment by CppPolska** [comment]
Doedukowałem się, byłem przeświadczony że tak się deklaruje istnienie metody/property (dwa pierwsze). Robi się to inaczej.

Dzięki! 👍

**Comment by CppPolska** [comment]
Temat niezakończonego wątku - chciałem zrobić to trochę inaczej. Przy wyjściu z gry chciałbym ustawić stan zmiennych wewnątrz wątku tak, by się zamknął i poczekać na to, aż się zakończy. Potem wyjść z wątku głównego.
